name: lyform
description: A new Flutter package project.
version: 0.1.4
homepage: https://github.com/lynotofficial/lynot-dart-flutter
repository: https://github.com/lynotofficial/lynot-dart-flutter/packages/lyform

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.2.0-dev.1
  collection: ^1.15.0

dev_dependencies:
  lint: ^1.5.3
  mocktail: ^0.1.4
  test: ^1.17.5
