name: lyform
description: Dart package to implement forms in an easy, fast and effective way using the bloc package
version: 0.3.1+1
homepage: https://github.com/lynotofficial/lynot-dart-flutter
repository: https://github.com/lynotofficial/lynot-dart-flutter/tree/master/packages/lyform

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bloc: ^7.2.0
  collection: ^1.15.0

dev_dependencies:
  lint: ^1.7.2
  mocktail: ^0.1.4
  test: ^1.17.12
