name: flutter_lyform
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/lynotofficial/flutter_lyform
repository: https://github.com/lynotofficial/flutter_lyform

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter_bloc: ^7.0.1
  lyform: ^0.0.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
