name: flutter_lyform
description: A new Flutter package project.
version: 0.1.0+11
homepage: https://github.com/lynotofficial/lynot-dart-flutter
repository: https://github.com/lynotofficial/lynot-dart-flutter/packages/flutter_lyform

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  lyform: ^0.2.0+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  mocktail: ^0.1.4
